---
title: "Lab 7 Rank-Based Tests"
author: "Alex Ivina"
date: "November 14, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Hi this is Alex and I created this awesome repo for you to admire.

```{r}

library(tidyverse)
kermit <- read_csv("kermit.csv")

kermit_hist <- ggplot(kermit, aes(x = Score.pre)) +
  geom_histogram() +
  facet_wrap(~ Gender)

kermit_hist

```

Creator: doing rank-based tests

```{r}

# Is there a significant difference in pre-talk Kermit scores for males and females?

# Unpaired: Mann-Whitney U

mwu_kermit <- kermit %>% 
  wilcox.test(Score.pre ~ Gender, data = .)

mwu_kermit


```

COLLABORATOR:

Now I want to compare the pre-talk and post talk ranks - 
"IS there a significant difference in Kermit ranks for pre-talk and post-talk scores (ignoring all other variables)?"

H0: No.

```{r}

wsr_kermit <- wilcox.test(kermit$Score.pre, kermit$Score.post, paired = TRUE)
wsr_kermit

# There is no significant difference in rankings before and after his talk (Summary...)

```


